import { NextRequest, NextResponse } from "next/server";
import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, ShadingType, AlignmentType, BorderStyle, HeadingLevel,
} from "docx";
import type { CanvasAssignment } from "@/lib/types";
import { COURSE_COLORS } from "@/lib/types";

function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.substring(0, 2), 16),
    g: parseInt(h.substring(2, 4), 16),
    b: parseInt(h.substring(4, 6), 16),
  };
}

function hexToBgr(hex: string) {
  // docx uses RRGGBB strings without #
  return hex.replace("#", "").toUpperCase();
}

// Light version of the accent color for answer boxes
function lightHex(hex: string) {
  const { r, g, b } = hexToRgb(hex);
  const lighten = (c: number) => Math.round(c + (255 - c) * 0.85);
  return [lighten(r), lighten(g), lighten(b)]
    .map((c) => c.toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase();
}

function formatDate(iso: string | null) {
  if (!iso) return "";
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
}

export async function POST(req: NextRequest) {
  try {
    const { assignment }: { assignment: CanvasAssignment; token: string } = await req.json();

    const accent  = hexToBgr(COURSE_COLORS[assignment.course_code] || "#555555");
    const light   = lightHex(COURSE_COLORS[assignment.course_code] || "#555555");

    const sections = [];

    // ── Header banner ────────────────────────────────────────────────────────
    sections.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                shading: { type: ShadingType.SOLID, color: accent, fill: accent },
                borders: {
                  top:    { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  left:   { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  right:  { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                },
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: `${assignment.course_code}  |  CLASS PREP  |  ${formatDate(assignment.due_at)}`,
                        bold: true,
                        color: "FFFFFF",
                        size: 18,
                        font: "Arial",
                      }),
                    ],
                    spacing: { before: 80, after: 80 },
                    indent: { left: 120 },
                  }),
                ],
              }),
            ],
          }),
        ],
      })
    );

    // ── Title ─────────────────────────────────────────────────────────────────
    sections.push(
      new Paragraph({
        children: [
          new TextRun({
            text: assignment.name,
            bold: true,
            size: 28,
            color: accent,
            font: "Arial",
          }),
        ],
        spacing: { before: 160, after: 60 },
        heading: HeadingLevel.HEADING_1,
      })
    );

    sections.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${assignment.course_name}  ·  Generated by HBS Canvas Sync`,
            italics: true,
            size: 18,
            color: "888888",
            font: "Arial",
          }),
        ],
        spacing: { before: 0, after: 200 },
      })
    );

    // ── Assignment Questions ──────────────────────────────────────────────────
    if (assignment.questions.length > 0) {
      sections.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "ASSIGNMENT QUESTIONS",
              bold: true,
              size: 20,
              color: accent,
              font: "Arial",
            }),
          ],
          spacing: { before: 200, after: 80 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: accent },
          },
        })
      );

      assignment.questions.forEach((q, i) => {
        // Question
        sections.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `Q${i + 1}: ${q}`,
                bold: true,
                size: 20,
                color: accent,
                font: "Arial",
              }),
            ],
            spacing: { before: 160, after: 60 },
          })
        );

        // Answer box (placeholder for the prototype)
        sections.push(
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    shading: { type: ShadingType.SOLID, color: light, fill: light },
                    borders: {
                      top:    { style: BorderStyle.NONE, size: 0, color: light },
                      bottom: { style: BorderStyle.NONE, size: 0, color: light },
                      left:   { style: BorderStyle.NONE, size: 0, color: light },
                      right:  { style: BorderStyle.NONE, size: 0, color: light },
                    },
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: "[Your analysis here — fill in before class]",
                            italics: true,
                            size: 20,
                            color: "666666",
                            font: "Arial",
                          }),
                        ],
                        spacing: { before: 80, after: 80 },
                        indent: { left: 120 },
                      }),
                    ],
                  }),
                ],
              }),
            ],
          })
        );
      });
    }

    // ── Notes section ─────────────────────────────────────────────────────────
    sections.push(
      new Paragraph({
        children: [
          new TextRun({
            text: "NOTES",
            bold: true,
            size: 20,
            color: accent,
            font: "Arial",
          }),
        ],
        spacing: { before: 240, after: 80 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: accent },
        },
      })
    );

    for (let i = 0; i < 6; i++) {
      sections.push(
        new Paragraph({
          children: [
            new TextRun({ text: "", size: 20, font: "Arial" }),
          ],
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 4, color: "DDDDDD" },
          },
          spacing: { before: 0, after: 200 },
        })
      );
    }

    // ── Build document ────────────────────────────────────────────────────────
    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: { top: 720, bottom: 720, left: 1080, right: 1080 },
          },
        },
        children: sections,
      }],
    });

    const buffer = await Packer.toBuffer(doc);

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${assignment.course_code}-cheatsheet.docx"`,
      },
    });
  } catch (e) {
    console.error("Cheat sheet error:", e);
    return NextResponse.json({ error: "Failed to generate cheat sheet." }, { status: 500 });
  }
}
